/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 draco_baseball.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Baseball(props) {
  const { nodes, materials } = useGLTF('/draco_baseball.gltf', true)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.baseball_01.geometry} material={materials.baseball_01} />
    </group>
  )
}

useGLTF.preload('/draco_baseball.gltf')
