services:
    portfolio-frontend:
      container_name: portfolio-frontend
      restart: unless-stopped
      volumes:
        - ./deploy/frontend.conf:/etc/nginx/templates/nginx.conf.template
        - ${SSL_DIR}${CERT}.crt:${NGINX_SSL_DIR}${CERT}.crt
        - ${SSL_DIR}${KEY}.key:${NGINX_SSL_DIR}${KEY}.key
      environment:
        NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
        CRT_LOCATION: ${NGINX_SSL_DIR}${CERT}.crt
        KEY_LOCATION: ${NGINX_SSL_DIR}${KEY}.key
      build:
        context: ./patrick-resume
        dockerfile: ./Deploy.dockerfile
      ports:
      - ${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}
      - ${HTTPS_PROXY_PORT}:${HTTPS_PROXY_PORT}